# Generated by Django 5.2.11 on 2026-03-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_activity_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_horas_day',
            field=models.IntegerField(default=24),
        ),
    ]
