# Generated by Django 5.2.11 on 2026-03-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_activity_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='priority_id',
            field=models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=2),
        ),
    ]
