# Generated by Django 5.2.11 on 2026-03-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_max_horas_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='max_horas_day',
            field=models.IntegerField(default=6),
        ),
    ]
