# Generated by Django 5.2.11 on 2026-03-14 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_activity_priority_id'),
        ('api', '0004_alter_user_max_horas_day'),
    ]

    operations = [
    ]
