# Generated by Django 5.2.11 on 2026-03-18 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20260314_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status_id',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'En Progreso'), (3, 'Completada'), (4, 'Cancelada'), (5, 'Pospuesta')], default=1),
        ),
        migrations.CreateModel(
            name='ActivityNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Razón/Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.activity')),
            ],
        ),
    ]
